#!/bin/bash

newtab () {
  osascript -e 'tell application "iTerm" to activate' -e 'tell application "System Events" to tell process "iTerm" to keystroke "t" using command down' -e 'tell application "System Events" to tell process "iTerm" to keystroke "'"$1"'"' -e 'tell application "System Events" to tell process "iTerm" to key code 52'
}

newtab /opt/local/mongodb/bin/mongod
newtab redis-server
newtab "node server/"

gulp watch
